//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Collection
{ 
    /// <summary>
    /// 收集品效果类型
    /// </summary>
    public enum EffectType
    {
        None = 0,
        /// <summary>
        /// 1:属性     奖励填写:[属性ID:属性值;属性ID:属性值]
        /// </summary>
        Attribute = 1,
        /// <summary>
        /// 2:增加pvp能量获取速度  奖励填写:[每秒提高的速度]
        /// </summary>
        MPCollectionSpeed = 2,
        /// <summary>
        /// 3:减少体力恢复的间隔    奖励填写:[减少值]
        /// </summary>
        ReducePowerRecoveryTime = 3,
        /// <summary>
        /// 4:变更块的生成几率      奖励填写:[块ID:几率;块ID:几率]
        /// </summary>
        ChangeBlockCreateRate = 4,
        /// <summary>
        /// 5:增加经验值的获取      奖励填写:[额外值]
        /// </summary>
        GetMoreEXP = 5,
        /// <summary>
        /// 6:增加荣誉值的获取      奖励填写:[额外值]
        /// </summary>
        GetMoreHonor = 6,
        /// <summary>
        /// 7:增加体力上限            奖励填写:[直接增加]
        /// </summary>
        MoreMaxPower = 7,
    }

} 
