//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class Attribute
{
    private readonly Dictionary<int, TbAttribute> _dataMap;
    private readonly List<TbAttribute> _dataList;
    
    public Attribute(JSONNode _json)
    {
        _dataMap = new Dictionary<int, TbAttribute>();
        _dataList = new List<TbAttribute>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = TbAttribute.DeserializeTbAttribute(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<int, TbAttribute> DataMap => _dataMap;
    public List<TbAttribute> DataList => _dataList;

    public TbAttribute GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TbAttribute Get(int key) => _dataMap[key];
    public TbAttribute this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}