//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class AttributeData :  Bright.Config.BeanBase 
{
    public AttributeData(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["value"].IsNumber) { throw new SerializationException(); }  Value = _json["value"]; }
        PostInit();
    }

    public AttributeData(int id, int value ) 
    {
        this.Id = id;
        this.Value = value;
        PostInit();
    }

    public static AttributeData DeserializeAttributeData(JSONNode _json)
    {
        return new AttributeData(_json);
    }

    /// <summary>
    /// 属性ID
    /// </summary>
    public int Id { get; private set; }
    public TbAttribute Id_Ref { get; private set; }
    /// <summary>
    /// 属性数值
    /// </summary>
    public int Value { get; private set; }

    public const int __ID__ = -650604474;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        this.Id_Ref = (_tables["Attribute"] as Attribute).GetOrDefault(Id);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Value:" + Value + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
