//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class BlockAnimation
{
    private readonly List<TbBlockAnimation> _dataList;
    
    private Dictionary<(int, int), TbBlockAnimation> _dataMapUnion;

    public BlockAnimation(JSONNode _json)
    {
        _dataList = new List<TbBlockAnimation>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = TbBlockAnimation.DeserializeTbBlockAnimation(_row);
            _dataList.Add(_v);
        }
        _dataMapUnion = new Dictionary<(int, int), TbBlockAnimation>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.ID, _v.Group), _v);
        }
        PostInit();
    }

    public List<TbBlockAnimation> DataList => _dataList;

    public TbBlockAnimation Get(int ID, int Group) => _dataMapUnion.TryGetValue((ID, Group), out TbBlockAnimation __v) ? __v : null;

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }

    
    partial void PostInit();
    partial void PostResolve();
}

}