//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class DiamondShop
{
    private readonly Dictionary<int, TbDiamondShop> _dataMap;
    private readonly List<TbDiamondShop> _dataList;
    
    public DiamondShop(JSONNode _json)
    {
        _dataMap = new Dictionary<int, TbDiamondShop>();
        _dataList = new List<TbDiamondShop>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = TbDiamondShop.DeserializeTbDiamondShop(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<int, TbDiamondShop> DataMap => _dataMap;
    public List<TbDiamondShop> DataList => _dataList;

    public TbDiamondShop GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TbDiamondShop Get(int key) => _dataMap[key];
    public TbDiamondShop this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}