//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class Grade
{
    private readonly Dictionary<int, TbGrade> _dataMap;
    private readonly List<TbGrade> _dataList;
    
    public Grade(JSONNode _json)
    {
        _dataMap = new Dictionary<int, TbGrade>();
        _dataList = new List<TbGrade>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = TbGrade.DeserializeTbGrade(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<int, TbGrade> DataMap => _dataMap;
    public List<TbGrade> DataList => _dataList;

    public TbGrade GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TbGrade Get(int key) => _dataMap[key];
    public TbGrade this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}