//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class Level
{
    private readonly Dictionary<int, TbLevel> _dataMap;
    private readonly List<TbLevel> _dataList;
    
    public Level(JSONNode _json)
    {
        _dataMap = new Dictionary<int, TbLevel>();
        _dataList = new List<TbLevel>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = TbLevel.DeserializeTbLevel(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<int, TbLevel> DataMap => _dataMap;
    public List<TbLevel> DataList => _dataList;

    public TbLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TbLevel Get(int key) => _dataMap[key];
    public TbLevel this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}