//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class Pokedex
{
    private readonly Dictionary<int, TbPokedex> _dataMap;
    private readonly List<TbPokedex> _dataList;
    
    public Pokedex(JSONNode _json)
    {
        _dataMap = new Dictionary<int, TbPokedex>();
        _dataList = new List<TbPokedex>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = TbPokedex.DeserializeTbPokedex(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<int, TbPokedex> DataMap => _dataMap;
    public List<TbPokedex> DataList => _dataList;

    public TbPokedex GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TbPokedex Get(int key) => _dataMap[key];
    public TbPokedex this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}