//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class RewardData :  Bright.Config.BeanBase 
{
    public RewardData(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["count"].IsNumber) { throw new SerializationException(); }  Count = _json["count"]; }
        PostInit();
    }

    public RewardData(int id, int count ) 
    {
        this.Id = id;
        this.Count = count;
        PostInit();
    }

    public static RewardData DeserializeRewardData(JSONNode _json)
    {
        return new RewardData(_json);
    }

    /// <summary>
    /// 道具ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 数量
    /// </summary>
    public int Count { get; private set; }

    public const int __ID__ = -610771047;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Count:" + Count + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
