//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbBlockGuide :  Bright.Config.BeanBase 
{
    public TbBlockGuide(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["Level"].IsNumber) { throw new SerializationException(); }  Level = _json["Level"]; }
        { if(!_json["BlockName"].IsString) { throw new SerializationException(); }  BlockName = _json["BlockName"]; }
        { if(!_json["Icon"].IsString) { throw new SerializationException(); }  Icon = _json["Icon"]; }
        { if(!_json["effect"].IsString) { throw new SerializationException(); }  Effect = _json["effect"]; }
        { if(!_json["Info1"].IsString) { throw new SerializationException(); }  Info1 = _json["Info1"]; }
        { if(!_json["Desc"].IsString) { throw new SerializationException(); }  Desc = _json["Desc"]; }
        { if(!_json["Evaluate"].IsNumber) { throw new SerializationException(); }  Evaluate = _json["Evaluate"]; }
        PostInit();
    }

    public TbBlockGuide(int ID, int Level, string BlockName, string Icon, string effect, string Info1, string Desc, int Evaluate ) 
    {
        this.ID = ID;
        this.Level = Level;
        this.BlockName = BlockName;
        this.Icon = Icon;
        this.Effect = effect;
        this.Info1 = Info1;
        this.Desc = Desc;
        this.Evaluate = Evaluate;
        PostInit();
    }

    public static TbBlockGuide DeserializeTbBlockGuide(JSONNode _json)
    {
        return new TbBlockGuide(_json);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 出现关卡
    /// </summary>
    public int Level { get; private set; }
    /// <summary>
    /// 滑块名称
    /// </summary>
    public string BlockName { get; private set; }
    /// <summary>
    /// 图标名称
    /// </summary>
    public string Icon { get; private set; }
    /// <summary>
    /// 特效路径
    /// </summary>
    public string Effect { get; private set; }
    /// <summary>
    /// 条目
    /// </summary>
    public string Info1 { get; private set; }
    /// <summary>
    /// 详细描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 评价
    /// </summary>
    public int Evaluate { get; private set; }

    public const int __ID__ = 1208345501;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Level:" + Level + ","
        + "BlockName:" + BlockName + ","
        + "Icon:" + Icon + ","
        + "Effect:" + Effect + ","
        + "Info1:" + Info1 + ","
        + "Desc:" + Desc + ","
        + "Evaluate:" + Evaluate + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
