//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbBlockOperationStep :  Bright.Config.BeanBase 
{
    public TbBlockOperationStep(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["X"].IsNumber) { throw new SerializationException(); }  X = _json["X"]; }
        { if(!_json["Y"].IsNumber) { throw new SerializationException(); }  Y = _json["Y"]; }
        { if(!_json["OperationType"].IsNumber) { throw new SerializationException(); }  OperationType = _json["OperationType"]; }
        { if(!_json["Pause"].IsBoolean) { throw new SerializationException(); }  Pause = _json["Pause"]; }
        { if(!_json["TriggerGuide"].IsNumber) { throw new SerializationException(); }  TriggerGuide = _json["TriggerGuide"]; }
        { if(!_json["NextStep"].IsNumber) { throw new SerializationException(); }  NextStep = _json["NextStep"]; }
        PostInit();
    }

    public TbBlockOperationStep(int ID, int X, int Y, int OperationType, bool Pause, int TriggerGuide, int NextStep ) 
    {
        this.ID = ID;
        this.X = X;
        this.Y = Y;
        this.OperationType = OperationType;
        this.Pause = Pause;
        this.TriggerGuide = TriggerGuide;
        this.NextStep = NextStep;
        PostInit();
    }

    public static TbBlockOperationStep DeserializeTbBlockOperationStep(JSONNode _json)
    {
        return new TbBlockOperationStep(_json);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// x
    /// </summary>
    public int X { get; private set; }
    /// <summary>
    /// y
    /// </summary>
    public int Y { get; private set; }
    /// <summary>
    /// 操作类型0 点击 1移动
    /// </summary>
    public int OperationType { get; private set; }
    /// <summary>
    /// 暂停游戏
    /// </summary>
    public bool Pause { get; private set; }
    /// <summary>
    /// 触发引导
    /// </summary>
    public int TriggerGuide { get; private set; }
    /// <summary>
    /// 下一个步骤
    /// </summary>
    public int NextStep { get; private set; }

    public const int __ID__ = -1669284748;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "X:" + X + ","
        + "Y:" + Y + ","
        + "OperationType:" + OperationType + ","
        + "Pause:" + Pause + ","
        + "TriggerGuide:" + TriggerGuide + ","
        + "NextStep:" + NextStep + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
