//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbBlockAnimation :  Bright.Config.BeanBase 
{
    public TbBlockAnimation(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["Group"].IsNumber) { throw new SerializationException(); }  Group = _json["Group"]; }
        { if(!_json["X"].IsNumber) { throw new SerializationException(); }  X = _json["X"]; }
        { if(!_json["Y"].IsNumber) { throw new SerializationException(); }  Y = _json["Y"]; }
        { if(!_json["Delay"].IsNumber) { throw new SerializationException(); }  Delay = _json["Delay"]; }
        { if(!_json["Duration"].IsNumber) { throw new SerializationException(); }  Duration = _json["Duration"]; }
        PostInit();
    }

    public TbBlockAnimation(int ID, int Group, int X, int Y, float Delay, float Duration ) 
    {
        this.ID = ID;
        this.Group = Group;
        this.X = X;
        this.Y = Y;
        this.Delay = Delay;
        this.Duration = Duration;
        PostInit();
    }

    public static TbBlockAnimation DeserializeTbBlockAnimation(JSONNode _json)
    {
        return new TbBlockAnimation(_json);
    }

    /// <summary>
    /// 角色ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 组
    /// </summary>
    public int Group { get; private set; }
    /// <summary>
    /// x
    /// </summary>
    public int X { get; private set; }
    /// <summary>
    /// y
    /// </summary>
    public int Y { get; private set; }
    /// <summary>
    /// 延迟时间
    /// </summary>
    public float Delay { get; private set; }
    /// <summary>
    /// 下落持续时间
    /// </summary>
    public float Duration { get; private set; }

    public const int __ID__ = 60263333;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Group:" + Group + ","
        + "X:" + X + ","
        + "Y:" + Y + ","
        + "Delay:" + Delay + ","
        + "Duration:" + Duration + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
