//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbDiamondShop :  Bright.Config.BeanBase 
{
    public TbDiamondShop(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["Diamond"].IsNumber) { throw new SerializationException(); }  Diamond = _json["Diamond"]; }
        { if(!_json["Price"].IsNumber) { throw new SerializationException(); }  Price = _json["Price"]; }
        { if(!_json["Discount"].IsString) { throw new SerializationException(); }  Discount = _json["Discount"]; }
        { if(!_json["IconName"].IsString) { throw new SerializationException(); }  IconName = _json["IconName"]; }
        PostInit();
    }

    public TbDiamondShop(int ID, int Diamond, int Price, string Discount, string IconName ) 
    {
        this.ID = ID;
        this.Diamond = Diamond;
        this.Price = Price;
        this.Discount = Discount;
        this.IconName = IconName;
        PostInit();
    }

    public static TbDiamondShop DeserializeTbDiamondShop(JSONNode _json)
    {
        return new TbDiamondShop(_json);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 获得钻石
    /// </summary>
    public int Diamond { get; private set; }
    /// <summary>
    /// 售价
    /// </summary>
    public int Price { get; private set; }
    /// <summary>
    /// 折扣
    /// </summary>
    public string Discount { get; private set; }
    /// <summary>
    /// 图标名称
    /// </summary>
    public string IconName { get; private set; }

    public const int __ID__ = 232636156;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Diamond:" + Diamond + ","
        + "Price:" + Price + ","
        + "Discount:" + Discount + ","
        + "IconName:" + IconName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
