//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbFunctionalOpening :  Bright.Config.BeanBase 
{
    public TbFunctionalOpening(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["Type"].IsNumber) { throw new SerializationException(); }  Type = _json["Type"]; }
        { if(!_json["Condition"].IsNumber) { throw new SerializationException(); }  Condition = _json["Condition"]; }
        { if(!_json["Tips"].IsString) { throw new SerializationException(); }  Tips = _json["Tips"]; }
        PostInit();
    }

    public TbFunctionalOpening(int ID, int Type, int Condition, string Tips ) 
    {
        this.ID = ID;
        this.Type = Type;
        this.Condition = Condition;
        this.Tips = Tips;
        PostInit();
    }

    public static TbFunctionalOpening DeserializeTbFunctionalOpening(JSONNode _json)
    {
        return new TbFunctionalOpening(_json);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 开启条件类型
    /// </summary>
    public int Type { get; private set; }
    /// <summary>
    /// 开启条件
    /// </summary>
    public int Condition { get; private set; }
    /// <summary>
    /// 未开启Tips
    /// </summary>
    public string Tips { get; private set; }

    public const int __ID__ = -1313264409;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Type:" + Type + ","
        + "Condition:" + Condition + ","
        + "Tips:" + Tips + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
