//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbI18N :  Bright.Config.BeanBase 
{
    public TbI18N(JSONNode _json) 
    {
        { if(!_json["key"].IsString) { throw new SerializationException(); }  Key = _json["key"]; }
        { if(!_json["zh_cn"].IsString) { throw new SerializationException(); }  ZhCn = _json["zh_cn"]; }
        { if(!_json["en"].IsString) { throw new SerializationException(); }  En = _json["en"]; }
        PostInit();
    }

    public TbI18N(string key, string zh_cn, string en ) 
    {
        this.Key = key;
        this.ZhCn = zh_cn;
        this.En = en;
        PostInit();
    }

    public static TbI18N DeserializeTbI18N(JSONNode _json)
    {
        return new TbI18N(_json);
    }

    /// <summary>
    /// 本地化key
    /// </summary>
    public string Key { get; private set; }
    /// <summary>
    /// 简体中文
    /// </summary>
    public string ZhCn { get; private set; }
    /// <summary>
    /// 英文
    /// </summary>
    public string En { get; private set; }

    public const int __ID__ = -1797389908;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "ZhCn:" + ZhCn + ","
        + "En:" + En + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
