//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbInterfaceText :  Bright.Config.BeanBase 
{
    public TbInterfaceText(JSONNode _json) 
    {
        { if(!_json["Key"].IsString) { throw new SerializationException(); }  Key = _json["Key"]; }
        { if(!_json["Text"]["key"].IsString) { throw new SerializationException(); }  Text_l10n_key = _json["Text"]["key"]; if(!_json["Text"]["text"].IsString) { throw new SerializationException(); }  Text = _json["Text"]["text"]; }
        PostInit();
    }

    public TbInterfaceText(string Key, string Text ) 
    {
        this.Key = Key;
        this.Text = Text;
        PostInit();
    }

    public static TbInterfaceText DeserializeTbInterfaceText(JSONNode _json)
    {
        return new TbInterfaceText(_json);
    }

    /// <summary>
    /// Key
    /// </summary>
    public string Key { get; private set; }
    /// <summary>
    /// 文本内容
    /// </summary>
    public string Text { get; private set; }
    public string Text_l10n_key { get; }

    public const int __ID__ = 1095179800;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        Text = translator(Text_l10n_key, Text);
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "Text:" + Text + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
