//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbMatchGroup :  Bright.Config.BeanBase 
{
    public TbMatchGroup(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["GroupID"].IsNumber) { throw new SerializationException(); }  GroupID = _json["GroupID"]; }
        { if(!_json["BolckID"].IsNumber) { throw new SerializationException(); }  BolckID = _json["BolckID"]; }
        { if(!_json["Odds"].IsNumber) { throw new SerializationException(); }  Odds = _json["Odds"]; }
        { if(!_json["MaxNumber"].IsNumber) { throw new SerializationException(); }  MaxNumber = _json["MaxNumber"]; }
        { if(!_json["round1"].IsNumber) { throw new SerializationException(); }  Round1 = _json["round1"]; }
        { if(!_json["rate1"].IsNumber) { throw new SerializationException(); }  Rate1 = _json["rate1"]; }
        { if(!_json["round2"].IsNumber) { throw new SerializationException(); }  Round2 = _json["round2"]; }
        { if(!_json["rate2"].IsNumber) { throw new SerializationException(); }  Rate2 = _json["rate2"]; }
        { if(!_json["round3"].IsNumber) { throw new SerializationException(); }  Round3 = _json["round3"]; }
        { if(!_json["rate3"].IsNumber) { throw new SerializationException(); }  Rate3 = _json["rate3"]; }
        PostInit();
    }

    public TbMatchGroup(int ID, int GroupID, int BolckID, int Odds, int MaxNumber, int round1, int rate1, int round2, int rate2, int round3, int rate3 ) 
    {
        this.ID = ID;
        this.GroupID = GroupID;
        this.BolckID = BolckID;
        this.Odds = Odds;
        this.MaxNumber = MaxNumber;
        this.Round1 = round1;
        this.Rate1 = rate1;
        this.Round2 = round2;
        this.Rate2 = rate2;
        this.Round3 = round3;
        this.Rate3 = rate3;
        PostInit();
    }

    public static TbMatchGroup DeserializeTbMatchGroup(JSONNode _json)
    {
        return new TbMatchGroup(_json);
    }

    /// <summary>
    /// 消除组ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 应用关卡 ID
    /// </summary>
    public int GroupID { get; private set; }
    /// <summary>
    /// 消除块ID
    /// </summary>
    public int BolckID { get; private set; }
    /// <summary>
    /// 出现概率
    /// </summary>
    public int Odds { get; private set; }
    /// <summary>
    /// 每局最大生成数量
    /// </summary>
    public int MaxNumber { get; private set; }
    /// <summary>
    /// 回合1
    /// </summary>
    public int Round1 { get; private set; }
    /// <summary>
    /// 调整概率1
    /// </summary>
    public int Rate1 { get; private set; }
    /// <summary>
    /// 回合2
    /// </summary>
    public int Round2 { get; private set; }
    /// <summary>
    /// 调整概率2
    /// </summary>
    public int Rate2 { get; private set; }
    /// <summary>
    /// 回合3
    /// </summary>
    public int Round3 { get; private set; }
    /// <summary>
    /// 调整概率3
    /// </summary>
    public int Rate3 { get; private set; }

    public const int __ID__ = 1786973416;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "GroupID:" + GroupID + ","
        + "BolckID:" + BolckID + ","
        + "Odds:" + Odds + ","
        + "MaxNumber:" + MaxNumber + ","
        + "Round1:" + Round1 + ","
        + "Rate1:" + Rate1 + ","
        + "Round2:" + Round2 + ","
        + "Rate2:" + Rate2 + ","
        + "Round3:" + Round3 + ","
        + "Rate3:" + Rate3 + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
