//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbProp :  Bright.Config.BeanBase 
{
    public TbProp(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["Name"].IsString) { throw new SerializationException(); }  Name = _json["Name"]; }
        { if(!_json["PropType"].IsNumber) { throw new SerializationException(); }  PropType = _json["PropType"]; }
        { if(!_json["PropDesc"].IsString) { throw new SerializationException(); }  PropDesc = _json["PropDesc"]; }
        { if(!_json["InBattleCount"].IsNumber) { throw new SerializationException(); }  InBattleCount = _json["InBattleCount"]; }
        { if(!_json["SkillID"].IsNumber) { throw new SerializationException(); }  SkillID = _json["SkillID"]; }
        { if(!_json["IconName"].IsString) { throw new SerializationException(); }  IconName = _json["IconName"]; }
        { if(!_json["Sort"].IsNumber) { throw new SerializationException(); }  Sort = _json["Sort"]; }
        { if(!_json["CoolDown"].IsNumber) { throw new SerializationException(); }  CoolDown = _json["CoolDown"]; }
        { if(!_json["TipsDesc"].IsString) { throw new SerializationException(); }  TipsDesc = _json["TipsDesc"]; }
        { if(!_json["TipsEnter"].IsString) { throw new SerializationException(); }  TipsEnter = _json["TipsEnter"]; }
        { if(!_json["TipsCancel"].IsString) { throw new SerializationException(); }  TipsCancel = _json["TipsCancel"]; }
        { if(!_json["BuffIcon"].IsString) { throw new SerializationException(); }  BuffIcon = _json["BuffIcon"]; }
        PostInit();
    }

    public TbProp(int ID, string Name, int PropType, string PropDesc, int InBattleCount, int SkillID, string IconName, int Sort, float CoolDown, string TipsDesc, string TipsEnter, string TipsCancel, string BuffIcon ) 
    {
        this.ID = ID;
        this.Name = Name;
        this.PropType = PropType;
        this.PropDesc = PropDesc;
        this.InBattleCount = InBattleCount;
        this.SkillID = SkillID;
        this.IconName = IconName;
        this.Sort = Sort;
        this.CoolDown = CoolDown;
        this.TipsDesc = TipsDesc;
        this.TipsEnter = TipsEnter;
        this.TipsCancel = TipsCancel;
        this.BuffIcon = BuffIcon;
        PostInit();
    }

    public static TbProp DeserializeTbProp(JSONNode _json)
    {
        return new TbProp(_json);
    }

    /// <summary>
    /// id
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 道具名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 道具类型
    /// </summary>
    public int PropType { get; private set; }
    /// <summary>
    /// 道具描述
    /// </summary>
    public string PropDesc { get; private set; }
    /// <summary>
    /// 最大单次携带量
    /// </summary>
    public int InBattleCount { get; private set; }
    /// <summary>
    /// 对应技能id
    /// </summary>
    public int SkillID { get; private set; }
    /// <summary>
    /// 图标名称
    /// </summary>
    public string IconName { get; private set; }
    /// <summary>
    /// 背包排序
    /// </summary>
    public int Sort { get; private set; }
    /// <summary>
    /// 战斗CD
    /// </summary>
    public float CoolDown { get; private set; }
    /// <summary>
    /// Tips 描述
    /// </summary>
    public string TipsDesc { get; private set; }
    /// <summary>
    /// Tips 确认文字
    /// </summary>
    public string TipsEnter { get; private set; }
    /// <summary>
    /// Tips 取消文字
    /// </summary>
    public string TipsCancel { get; private set; }
    /// <summary>
    /// buff图标
    /// </summary>
    public string BuffIcon { get; private set; }

    public const int __ID__ = -1797117167;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "PropType:" + PropType + ","
        + "PropDesc:" + PropDesc + ","
        + "InBattleCount:" + InBattleCount + ","
        + "SkillID:" + SkillID + ","
        + "IconName:" + IconName + ","
        + "Sort:" + Sort + ","
        + "CoolDown:" + CoolDown + ","
        + "TipsDesc:" + TipsDesc + ","
        + "TipsEnter:" + TipsEnter + ","
        + "TipsCancel:" + TipsCancel + ","
        + "BuffIcon:" + BuffIcon + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
