//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbPVPLevel :  Bright.Config.BeanBase 
{
    public TbPVPLevel(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["Name"].IsString) { throw new SerializationException(); }  Name = _json["Name"]; }
        { if(!_json["SceneID"].IsNumber) { throw new SerializationException(); }  SceneID = _json["SceneID"]; }
        { if(!_json["MatchStoreID"].IsNumber) { throw new SerializationException(); }  MatchStoreID = _json["MatchStoreID"]; }
        { if(!_json["BattleTime"].IsNumber) { throw new SerializationException(); }  BattleTime = _json["BattleTime"]; }
        { if(!_json["HPFactor"].IsNumber) { throw new SerializationException(); }  HPFactor = _json["HPFactor"]; }
        { if(!_json["DamageFactor"].IsNumber) { throw new SerializationException(); }  DamageFactor = _json["DamageFactor"]; }
        PostInit();
    }

    public TbPVPLevel(int ID, string Name, int SceneID, int MatchStoreID, int BattleTime, float HPFactor, float DamageFactor ) 
    {
        this.ID = ID;
        this.Name = Name;
        this.SceneID = SceneID;
        this.MatchStoreID = MatchStoreID;
        this.BattleTime = BattleTime;
        this.HPFactor = HPFactor;
        this.DamageFactor = DamageFactor;
        PostInit();
    }

    public static TbPVPLevel DeserializeTbPVPLevel(JSONNode _json)
    {
        return new TbPVPLevel(_json);
    }

    /// <summary>
    /// 关卡ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 关卡名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 场景资源ID
    /// </summary>
    public int SceneID { get; private set; }
    /// <summary>
    /// 消除库 ID
    /// </summary>
    public int MatchStoreID { get; private set; }
    /// <summary>
    /// 时间
    /// </summary>
    public int BattleTime { get; private set; }
    /// <summary>
    /// 血量调整
    /// </summary>
    public float HPFactor { get; private set; }
    /// <summary>
    /// 攻击调整
    /// </summary>
    public float DamageFactor { get; private set; }

    public const int __ID__ = -1293687000;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "SceneID:" + SceneID + ","
        + "MatchStoreID:" + MatchStoreID + ","
        + "BattleTime:" + BattleTime + ","
        + "HPFactor:" + HPFactor + ","
        + "DamageFactor:" + DamageFactor + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
