//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbPVPRanking :  Bright.Config.BeanBase 
{
    public TbPVPRanking(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["TargetID"].IsString) { throw new SerializationException(); }  TargetID = _json["TargetID"]; }
        { if(!_json["Score"].IsNumber) { throw new SerializationException(); }  Score = _json["Score"]; }
        PostInit();
    }

    public TbPVPRanking(int ID, string TargetID, int Score ) 
    {
        this.ID = ID;
        this.TargetID = TargetID;
        this.Score = Score;
        PostInit();
    }

    public static TbPVPRanking DeserializeTbPVPRanking(JSONNode _json)
    {
        return new TbPVPRanking(_json);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 目标
    /// </summary>
    public string TargetID { get; private set; }
    /// <summary>
    /// 分数
    /// </summary>
    public int Score { get; private set; }

    public const int __ID__ = -1079329062;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "TargetID:" + TargetID + ","
        + "Score:" + Score + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
