//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbShop :  Bright.Config.BeanBase 
{
    public TbShop(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["Name"].IsString) { throw new SerializationException(); }  Name = _json["Name"]; }
        { if(!_json["Type"].IsNumber) { throw new SerializationException(); }  Type = _json["Type"]; }
        { if(!_json["Target"].IsNumber) { throw new SerializationException(); }  Target = _json["Target"]; }
        { if(!_json["Price"].IsNumber) { throw new SerializationException(); }  Price = _json["Price"]; }
        { if(!_json["Count"].IsNumber) { throw new SerializationException(); }  Count = _json["Count"]; }
        { if(!_json["ShopType"].IsNumber) { throw new SerializationException(); }  ShopType = _json["ShopType"]; }
        PostInit();
    }

    public TbShop(int ID, string Name, int Type, int Target, int Price, int Count, int ShopType ) 
    {
        this.ID = ID;
        this.Name = Name;
        this.Type = Type;
        this.Target = Target;
        this.Price = Price;
        this.Count = Count;
        this.ShopType = ShopType;
        PostInit();
    }

    public static TbShop DeserializeTbShop(JSONNode _json)
    {
        return new TbShop(_json);
    }

    /// <summary>
    /// id
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public int Type { get; private set; }
    /// <summary>
    /// 目标id
    /// </summary>
    public int Target { get; private set; }
    /// <summary>
    /// 价格
    /// </summary>
    public int Price { get; private set; }
    /// <summary>
    /// 购买次数
    /// </summary>
    public int Count { get; private set; }
    /// <summary>
    /// 商城类型
    /// </summary>
    public int ShopType { get; private set; }

    public const int __ID__ = -1797037404;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "Target:" + Target + ","
        + "Price:" + Price + ","
        + "Count:" + Count + ","
        + "ShopType:" + ShopType + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
