//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbSkill :  Bright.Config.BeanBase 
{
    public TbSkill(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["Name"].IsString) { throw new SerializationException(); }  Name = _json["Name"]; }
        { if(!_json["Icon"].IsString) { throw new SerializationException(); }  Icon = _json["Icon"]; }
        { if(!_json["MaxLevel"].IsNumber) { throw new SerializationException(); }  MaxLevel = _json["MaxLevel"]; }
        { if(!_json["Desc"].IsString) { throw new SerializationException(); }  Desc = _json["Desc"]; }
        { if(!_json["A"].IsNumber) { throw new SerializationException(); }  A = _json["A"]; }
        { if(!_json["B"].IsNumber) { throw new SerializationException(); }  B = _json["B"]; }
        PostInit();
    }

    public TbSkill(int ID, string Name, string Icon, int MaxLevel, string Desc, int A, int B ) 
    {
        this.ID = ID;
        this.Name = Name;
        this.Icon = Icon;
        this.MaxLevel = MaxLevel;
        this.Desc = Desc;
        this.A = A;
        this.B = B;
        PostInit();
    }

    public static TbSkill DeserializeTbSkill(JSONNode _json)
    {
        return new TbSkill(_json);
    }

    /// <summary>
    /// id
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 角色名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 图标
    /// </summary>
    public string Icon { get; private set; }
    /// <summary>
    /// 最大等级
    /// </summary>
    public int MaxLevel { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 基础比率
    /// </summary>
    public int A { get; private set; }
    /// <summary>
    /// 成长率
    /// </summary>
    public int B { get; private set; }

    public const int __ID__ = 126498915;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Icon:" + Icon + ","
        + "MaxLevel:" + MaxLevel + ","
        + "Desc:" + Desc + ","
        + "A:" + A + ","
        + "B:" + B + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
