//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbStarLevelReward :  Bright.Config.BeanBase 
{
    public TbStarLevelReward(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["StarCount"].IsNumber) { throw new SerializationException(); }  StarCount = _json["StarCount"]; }
        { if(!_json["Reward"].IsString) { throw new SerializationException(); }  Reward = _json["Reward"]; }
        PostInit();
    }

    public TbStarLevelReward(int ID, int StarCount, string Reward ) 
    {
        this.ID = ID;
        this.StarCount = StarCount;
        this.Reward = Reward;
        PostInit();
    }

    public static TbStarLevelReward DeserializeTbStarLevelReward(JSONNode _json)
    {
        return new TbStarLevelReward(_json);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 星星数量
    /// </summary>
    public int StarCount { get; private set; }
    /// <summary>
    /// 奖励
    /// </summary>
    public string Reward { get; private set; }

    public const int __ID__ = -468877901;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "StarCount:" + StarCount + ","
        + "Reward:" + Reward + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
