//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Achieventment
{ 
    /// <summary>
    /// 成就完成条件类型
    /// </summary>
    public enum Condition
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 杀死指定怪物
        /// </summary>
        KillMonster = 1,
        /// <summary>
        /// pve战斗胜利
        /// </summary>
        PVEWin = 2,
        /// <summary>
        /// pve失败
        /// </summary>
        PVEFail = 3,
        /// <summary>
        /// pvp胜利
        /// </summary>
        PVPWin = 4,
        /// <summary>
        /// pvp失败
        /// </summary>
        PVPFail = 5,
        /// <summary>
        /// pvp连胜次数
        /// </summary>
        PVPWinStreak = 6,
        /// <summary>
        /// 获取指定英雄
        /// </summary>
        GetHero = 7,
        /// <summary>
        /// 拥有英雄数量
        /// </summary>
        HeroCount = 8,
        /// <summary>
        /// 完成成就数量
        /// </summary>
        AchievementCompleteCount = 9,
        /// <summary>
        /// 获取物品数量
        /// </summary>
        GetItemCount = 10,
        /// <summary>
        /// 英雄最高等级
        /// </summary>
        HeroMaxLevel = 11,
        /// <summary>
        /// 团队最高等级
        /// </summary>
        TeamMaxLevel = 12,
        /// <summary>
        /// 累计获得经验值
        /// </summary>
        TotalEXP = 13,
        /// <summary>
        /// 累计消耗体力
        /// </summary>
        ConsumePower = 14,
        /// <summary>
        /// 累计获得的荣誉值
        /// </summary>
        HonorCount = 15,
        /// <summary>
        /// 累计使用道具
        /// </summary>
        UseItemCount = 16,
        /// <summary>
        /// 累计获得的PVP宝箱
        /// </summary>
        GetPVPBoxCount = 17,
        /// <summary>
        /// 累计开启的PVP宝箱
        /// </summary>
        UsePVPBoxCount = 18,
        /// <summary>
        /// 累计开启的宝箱库总数
        /// </summary>
        UnlockBoxSlotCount = 19,
        /// <summary>
        /// 完成指定成就组
        /// </summary>
        CompleteAchievementGroup = 20,
        /// <summary>
        /// 通过指定关卡
        /// </summary>
        FinishLevel = 21,
    }

} 
