//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class FunctionalOpening
{
    private readonly Dictionary<int, TbFunctionalOpening> _dataMap;
    private readonly List<TbFunctionalOpening> _dataList;
    
    public FunctionalOpening(JSONNode _json)
    {
        _dataMap = new Dictionary<int, TbFunctionalOpening>();
        _dataList = new List<TbFunctionalOpening>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = TbFunctionalOpening.DeserializeTbFunctionalOpening(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<int, TbFunctionalOpening> DataMap => _dataMap;
    public List<TbFunctionalOpening> DataList => _dataList;

    public TbFunctionalOpening GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TbFunctionalOpening Get(int key) => _dataMap[key];
    public TbFunctionalOpening this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}