//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class GradeConditionDesc
{
    private readonly Dictionary<int, TbGradeConditionDesc> _dataMap;
    private readonly List<TbGradeConditionDesc> _dataList;
    
    public GradeConditionDesc(JSONNode _json)
    {
        _dataMap = new Dictionary<int, TbGradeConditionDesc>();
        _dataList = new List<TbGradeConditionDesc>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = TbGradeConditionDesc.DeserializeTbGradeConditionDesc(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<int, TbGradeConditionDesc> DataMap => _dataMap;
    public List<TbGradeConditionDesc> DataList => _dataList;

    public TbGradeConditionDesc GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TbGradeConditionDesc Get(int key) => _dataMap[key];
    public TbGradeConditionDesc this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}