//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class RandomName
{
    private readonly Dictionary<int, TbRandomName> _dataMap;
    private readonly List<TbRandomName> _dataList;
    
    public RandomName(JSONNode _json)
    {
        _dataMap = new Dictionary<int, TbRandomName>();
        _dataList = new List<TbRandomName>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = TbRandomName.DeserializeTbRandomName(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, TbRandomName> DataMap => _dataMap;
    public List<TbRandomName> DataList => _dataList;

    public TbRandomName GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TbRandomName Get(int key) => _dataMap[key];
    public TbRandomName this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}