//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class Skill
{
    private readonly Dictionary<int, TbSkill> _dataMap;
    private readonly List<TbSkill> _dataList;
    
    public Skill(JSONNode _json)
    {
        _dataMap = new Dictionary<int, TbSkill>();
        _dataList = new List<TbSkill>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = TbSkill.DeserializeTbSkill(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<int, TbSkill> DataMap => _dataMap;
    public List<TbSkill> DataList => _dataList;

    public TbSkill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TbSkill Get(int key) => _dataMap[key];
    public TbSkill this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}