//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbActor :  Bright.Config.BeanBase 
{
    public TbActor(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["Name"].IsString) { throw new SerializationException(); }  Name = _json["Name"]; }
        { if(!_json["Trait"].IsNumber) { throw new SerializationException(); }  Trait = _json["Trait"]; }
        { var _json2 = _json["Position"]; if(!_json2.IsObject) { throw new SerializationException(); }  float __x; { if(!_json2["x"].IsNumber) { throw new SerializationException(); }  __x = _json2["x"]; } float __y; { if(!_json2["y"].IsNumber) { throw new SerializationException(); }  __y = _json2["y"]; } Position = new UnityEngine.Vector2(__x, __y); }
        { if(!_json["Icon2"].IsString) { throw new SerializationException(); }  Icon2 = _json["Icon2"]; }
        { if(!_json["Icon"].IsString) { throw new SerializationException(); }  Icon = _json["Icon"]; }
        { if(!_json["Desc"].IsString) { throw new SerializationException(); }  Desc = _json["Desc"]; }
        { if(!_json["ModelFullName"].IsString) { throw new SerializationException(); }  ModelFullName = _json["ModelFullName"]; }
        { if(!_json["ModelScale"].IsNumber) { throw new SerializationException(); }  ModelScale = _json["ModelScale"]; }
        { if(!_json["UseBirthAnim"].IsBoolean) { throw new SerializationException(); }  UseBirthAnim = _json["UseBirthAnim"]; }
        { if(!_json["WeaponModelPath"].IsString) { throw new SerializationException(); }  WeaponModelPath = _json["WeaponModelPath"]; }
        { if(!_json["WeaponModelScale"].IsNumber) { throw new SerializationException(); }  WeaponModelScale = _json["WeaponModelScale"]; }
        { if(!_json["OffHandModelPath"].IsString) { throw new SerializationException(); }  OffHandModelPath = _json["OffHandModelPath"]; }
        { if(!_json["OffHandModelScale"].IsNumber) { throw new SerializationException(); }  OffHandModelScale = _json["OffHandModelScale"]; }
        { if(!_json["WaistModelPath"].IsString) { throw new SerializationException(); }  WaistModelPath = _json["WaistModelPath"]; }
        { if(!_json["WaistModelScale"].IsNumber) { throw new SerializationException(); }  WaistModelScale = _json["WaistModelScale"]; }
        { if(!_json["HatModelPath"].IsString) { throw new SerializationException(); }  HatModelPath = _json["HatModelPath"]; }
        { if(!_json["HatModelScale"].IsNumber) { throw new SerializationException(); }  HatModelScale = _json["HatModelScale"]; }
        { if(!_json["CloakModelPath"].IsString) { throw new SerializationException(); }  CloakModelPath = _json["CloakModelPath"]; }
        { if(!_json["CloakModelScale"].IsNumber) { throw new SerializationException(); }  CloakModelScale = _json["CloakModelScale"]; }
        { var __json0 = _json["Attribute"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Attribute = new AttributeData[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { AttributeData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = AttributeData.DeserializeAttributeData(__e0);  }  Attribute[__index0++] = __v0; }   }
        { var __json0 = _json["Skills1"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Skills1 = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Skills1[__index0++] = __v0; }   }
        { var __json0 = _json["Skills2"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Skills2 = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Skills2[__index0++] = __v0; }   }
        { if(!_json["Skills3"].IsNumber) { throw new SerializationException(); }  Skills3 = _json["Skills3"]; }
        { if(!_json["Skills4"].IsString) { throw new SerializationException(); }  Skills4 = _json["Skills4"]; }
        { if(!_json["SoundTalk"].IsString) { throw new SerializationException(); }  SoundTalk = _json["SoundTalk"]; }
        PostInit();
    }

    public TbActor(int ID, string Name, int Trait, UnityEngine.Vector2 Position, string Icon2, string Icon, string Desc, string ModelFullName, float ModelScale, bool UseBirthAnim, string WeaponModelPath, float WeaponModelScale, string OffHandModelPath, float OffHandModelScale, string WaistModelPath, float WaistModelScale, string HatModelPath, float HatModelScale, string CloakModelPath, float CloakModelScale, AttributeData[] Attribute, int[] Skills1, int[] Skills2, int Skills3, string Skills4, string SoundTalk ) 
    {
        this.ID = ID;
        this.Name = Name;
        this.Trait = Trait;
        this.Position = Position;
        this.Icon2 = Icon2;
        this.Icon = Icon;
        this.Desc = Desc;
        this.ModelFullName = ModelFullName;
        this.ModelScale = ModelScale;
        this.UseBirthAnim = UseBirthAnim;
        this.WeaponModelPath = WeaponModelPath;
        this.WeaponModelScale = WeaponModelScale;
        this.OffHandModelPath = OffHandModelPath;
        this.OffHandModelScale = OffHandModelScale;
        this.WaistModelPath = WaistModelPath;
        this.WaistModelScale = WaistModelScale;
        this.HatModelPath = HatModelPath;
        this.HatModelScale = HatModelScale;
        this.CloakModelPath = CloakModelPath;
        this.CloakModelScale = CloakModelScale;
        this.Attribute = Attribute;
        this.Skills1 = Skills1;
        this.Skills2 = Skills2;
        this.Skills3 = Skills3;
        this.Skills4 = Skills4;
        this.SoundTalk = SoundTalk;
        PostInit();
    }

    public static TbActor DeserializeTbActor(JSONNode _json)
    {
        return new TbActor(_json);
    }

    /// <summary>
    /// 角色ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 角色名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 角色特性
    /// </summary>
    public int Trait { get; private set; }
    /// <summary>
    /// 半身头像Position
    /// </summary>
    public UnityEngine.Vector2 Position { get; private set; }
    /// <summary>
    /// 半身头像icon
    /// </summary>
    public string Icon2 { get; private set; }
    /// <summary>
    /// 头像icon
    /// </summary>
    public string Icon { get; private set; }
    /// <summary>
    /// 角色描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 模型路径
    /// </summary>
    public string ModelFullName { get; private set; }
    /// <summary>
    /// 模型比例
    /// </summary>
    public float ModelScale { get; private set; }
    /// <summary>
    /// 是否使用出生动画
    /// </summary>
    public bool UseBirthAnim { get; private set; }
    /// <summary>
    /// 武器模型路径
    /// </summary>
    public string WeaponModelPath { get; private set; }
    /// <summary>
    /// 武器模型比例
    /// </summary>
    public float WeaponModelScale { get; private set; }
    /// <summary>
    /// 副手模型路径
    /// </summary>
    public string OffHandModelPath { get; private set; }
    /// <summary>
    /// 副手模型比例
    /// </summary>
    public float OffHandModelScale { get; private set; }
    /// <summary>
    /// 腰部模型路径
    /// </summary>
    public string WaistModelPath { get; private set; }
    /// <summary>
    /// 腰部模型比例
    /// </summary>
    public float WaistModelScale { get; private set; }
    /// <summary>
    /// 帽子模型路径
    /// </summary>
    public string HatModelPath { get; private set; }
    /// <summary>
    /// 帽子模型比例
    /// </summary>
    public float HatModelScale { get; private set; }
    /// <summary>
    /// 披风模型路径
    /// </summary>
    public string CloakModelPath { get; private set; }
    /// <summary>
    /// 披风模型比例
    /// </summary>
    public float CloakModelScale { get; private set; }
    /// <summary>
    /// 基础属性
    /// </summary>
    public AttributeData[] Attribute { get; private set; }
    /// <summary>
    /// 天赋1层
    /// </summary>
    public int[] Skills1 { get; private set; }
    /// <summary>
    /// 触发技能
    /// </summary>
    public int[] Skills2 { get; private set; }
    /// <summary>
    /// PV主动P技能
    /// </summary>
    public int Skills3 { get; private set; }
    /// <summary>
    /// PVP被动技能
    /// </summary>
    public string Skills4 { get; private set; }
    /// <summary>
    /// 日常对话内容
    /// </summary>
    public string SoundTalk { get; private set; }

    public const int __ID__ = 109647879;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in Attribute) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in Attribute) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Trait:" + Trait + ","
        + "Position:" + Position + ","
        + "Icon2:" + Icon2 + ","
        + "Icon:" + Icon + ","
        + "Desc:" + Desc + ","
        + "ModelFullName:" + ModelFullName + ","
        + "ModelScale:" + ModelScale + ","
        + "UseBirthAnim:" + UseBirthAnim + ","
        + "WeaponModelPath:" + WeaponModelPath + ","
        + "WeaponModelScale:" + WeaponModelScale + ","
        + "OffHandModelPath:" + OffHandModelPath + ","
        + "OffHandModelScale:" + OffHandModelScale + ","
        + "WaistModelPath:" + WaistModelPath + ","
        + "WaistModelScale:" + WaistModelScale + ","
        + "HatModelPath:" + HatModelPath + ","
        + "HatModelScale:" + HatModelScale + ","
        + "CloakModelPath:" + CloakModelPath + ","
        + "CloakModelScale:" + CloakModelScale + ","
        + "Attribute:" + Bright.Common.StringUtil.CollectionToString(Attribute) + ","
        + "Skills1:" + Bright.Common.StringUtil.CollectionToString(Skills1) + ","
        + "Skills2:" + Bright.Common.StringUtil.CollectionToString(Skills2) + ","
        + "Skills3:" + Skills3 + ","
        + "Skills4:" + Skills4 + ","
        + "SoundTalk:" + SoundTalk + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
