//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbBox :  Bright.Config.BeanBase 
{
    public TbBox(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["Name"].IsString) { throw new SerializationException(); }  Name = _json["Name"]; }
        { if(!_json["Desc"].IsString) { throw new SerializationException(); }  Desc = _json["Desc"]; }
        { if(!_json["Duration"].IsNumber) { throw new SerializationException(); }  Duration = _json["Duration"]; }
        { if(!_json["IconName"].IsString) { throw new SerializationException(); }  IconName = _json["IconName"]; }
        { if(!_json["Diamond"].IsNumber) { throw new SerializationException(); }  Diamond = _json["Diamond"]; }
        PostInit();
    }

    public TbBox(int ID, string Name, string Desc, int Duration, string IconName, int Diamond ) 
    {
        this.ID = ID;
        this.Name = Name;
        this.Desc = Desc;
        this.Duration = Duration;
        this.IconName = IconName;
        this.Diamond = Diamond;
        PostInit();
    }

    public static TbBox DeserializeTbBox(JSONNode _json)
    {
        return new TbBox(_json);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 宝箱名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 宝箱说明
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 开启需要的时间(分钟)
    /// </summary>
    public int Duration { get; private set; }
    /// <summary>
    /// 图标名称
    /// </summary>
    public string IconName { get; private set; }
    /// <summary>
    /// 钻石消耗
    /// </summary>
    public int Diamond { get; private set; }

    public const int __ID__ = 80562269;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "Duration:" + Duration + ","
        + "IconName:" + IconName + ","
        + "Diamond:" + Diamond + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
