//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbDrop :  Bright.Config.BeanBase 
{
    public TbDrop(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["boxId"].IsNumber) { throw new SerializationException(); }  BoxId = _json["boxId"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { if(!_json["type"].IsNumber) { throw new SerializationException(); }  Type = _json["type"]; }
        { if(!_json["targetId"].IsNumber) { throw new SerializationException(); }  TargetId = _json["targetId"]; }
        { if(!_json["targetNumber"].IsNumber) { throw new SerializationException(); }  TargetNumber = _json["targetNumber"]; }
        { if(!_json["unique"].IsBoolean) { throw new SerializationException(); }  Unique = _json["unique"]; }
        { if(!_json["rate"].IsNumber) { throw new SerializationException(); }  Rate = _json["rate"]; }
        { var __json0 = _json["dropNumber"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; DropNumber = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  DropNumber[__index0++] = __v0; }   }
        PostInit();
    }

    public TbDrop(int id, int boxId, string name, int type, int targetId, int targetNumber, bool unique, int rate, int[] dropNumber ) 
    {
        this.Id = id;
        this.BoxId = boxId;
        this.Name = name;
        this.Type = type;
        this.TargetId = targetId;
        this.TargetNumber = targetNumber;
        this.Unique = unique;
        this.Rate = rate;
        this.DropNumber = dropNumber;
        PostInit();
    }

    public static TbDrop DeserializeTbDrop(JSONNode _json)
    {
        return new TbDrop(_json);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 掉落组
    /// </summary>
    public int BoxId { get; private set; }
    /// <summary>
    /// 宝箱名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 奖励类型
    /// </summary>
    public int Type { get; private set; }
    /// <summary>
    /// 目标id
    /// </summary>
    public int TargetId { get; private set; }
    /// <summary>
    /// 数量
    /// </summary>
    public int TargetNumber { get; private set; }
    /// <summary>
    /// 是否唯一
    /// </summary>
    public bool Unique { get; private set; }
    /// <summary>
    /// 出现几率
    /// </summary>
    public int Rate { get; private set; }
    /// <summary>
    /// 总掉落数
    /// </summary>
    public int[] DropNumber { get; private set; }

    public const int __ID__ = -1797474659;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "BoxId:" + BoxId + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "TargetId:" + TargetId + ","
        + "TargetNumber:" + TargetNumber + ","
        + "Unique:" + Unique + ","
        + "Rate:" + Rate + ","
        + "DropNumber:" + Bright.Common.StringUtil.CollectionToString(DropNumber) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
