//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbDungeon :  Bright.Config.BeanBase 
{
    public TbDungeon(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["StoreID"].IsNumber) { throw new SerializationException(); }  StoreID = _json["StoreID"]; }
        { if(!_json["Index"].IsNumber) { throw new SerializationException(); }  Index = _json["Index"]; }
        { if(!_json["LevelID"].IsNumber) { throw new SerializationException(); }  LevelID = _json["LevelID"]; }
        { if(!_json["Title"].IsString) { throw new SerializationException(); }  Title = _json["Title"]; }
        { var __json0 = _json["Reward"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Reward = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Reward[__index0++] = __v0; }   }
        { if(!_json["RewardDesc"].IsString) { throw new SerializationException(); }  RewardDesc = _json["RewardDesc"]; }
        { if(!_json["StoryDesc"].IsString) { throw new SerializationException(); }  StoryDesc = _json["StoryDesc"]; }
        { if(!_json["Power"].IsNumber) { throw new SerializationException(); }  Power = _json["Power"]; }
        PostInit();
    }

    public TbDungeon(int ID, int StoreID, int Index, int LevelID, string Title, int[] Reward, string RewardDesc, string StoryDesc, int Power ) 
    {
        this.ID = ID;
        this.StoreID = StoreID;
        this.Index = Index;
        this.LevelID = LevelID;
        this.Title = Title;
        this.Reward = Reward;
        this.RewardDesc = RewardDesc;
        this.StoryDesc = StoryDesc;
        this.Power = Power;
        PostInit();
    }

    public static TbDungeon DeserializeTbDungeon(JSONNode _json)
    {
        return new TbDungeon(_json);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 仓库 ID
    /// </summary>
    public int StoreID { get; private set; }
    /// <summary>
    /// 排序 ID
    /// </summary>
    public int Index { get; private set; }
    /// <summary>
    /// 关卡 ID
    /// </summary>
    public int LevelID { get; private set; }
    /// <summary>
    /// 条目名称
    /// </summary>
    public string Title { get; private set; }
    /// <summary>
    /// 奖励
    /// </summary>
    public int[] Reward { get; private set; }
    /// <summary>
    /// 奖励描述
    /// </summary>
    public string RewardDesc { get; private set; }
    /// <summary>
    /// 简介
    /// </summary>
    public string StoryDesc { get; private set; }
    /// <summary>
    /// 消耗体力
    /// </summary>
    public int Power { get; private set; }

    public const int __ID__ = 1169476684;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "StoreID:" + StoreID + ","
        + "Index:" + Index + ","
        + "LevelID:" + LevelID + ","
        + "Title:" + Title + ","
        + "Reward:" + Bright.Common.StringUtil.CollectionToString(Reward) + ","
        + "RewardDesc:" + RewardDesc + ","
        + "StoryDesc:" + StoryDesc + ","
        + "Power:" + Power + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
