//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbIcon :  Bright.Config.BeanBase 
{
    public TbIcon(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["Name"].IsString) { throw new SerializationException(); }  Name = _json["Name"]; }
        { if(!_json["Trait"].IsBoolean) { throw new SerializationException(); }  Trait = _json["Trait"]; }
        PostInit();
    }

    public TbIcon(int ID, string Name, bool Trait ) 
    {
        this.ID = ID;
        this.Name = Name;
        this.Trait = Trait;
        PostInit();
    }

    public static TbIcon DeserializeTbIcon(JSONNode _json)
    {
        return new TbIcon(_json);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 图片地址
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 初始解锁
    /// </summary>
    public bool Trait { get; private set; }

    public const int __ID__ = -1797340121;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Trait:" + Trait + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
