//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbLevelMap :  Bright.Config.BeanBase 
{
    public TbLevelMap(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["MapBlockID"].IsNumber) { throw new SerializationException(); }  MapBlockID = _json["MapBlockID"]; }
        { if(!_json["MapName"].IsString) { throw new SerializationException(); }  MapName = _json["MapName"]; }
        { if(!_json["Point1"].IsNumber) { throw new SerializationException(); }  Point1 = _json["Point1"]; }
        { if(!_json["Point2"].IsNumber) { throw new SerializationException(); }  Point2 = _json["Point2"]; }
        { if(!_json["Point3"].IsNumber) { throw new SerializationException(); }  Point3 = _json["Point3"]; }
        { if(!_json["Point4"].IsNumber) { throw new SerializationException(); }  Point4 = _json["Point4"]; }
        { if(!_json["Point5"].IsNumber) { throw new SerializationException(); }  Point5 = _json["Point5"]; }
        { if(!_json["Point1Offset"].IsString) { throw new SerializationException(); }  Point1Offset = _json["Point1Offset"]; }
        { if(!_json["Point2Offset"].IsString) { throw new SerializationException(); }  Point2Offset = _json["Point2Offset"]; }
        { if(!_json["Point3Offset"].IsString) { throw new SerializationException(); }  Point3Offset = _json["Point3Offset"]; }
        { if(!_json["Point4Offset"].IsString) { throw new SerializationException(); }  Point4Offset = _json["Point4Offset"]; }
        { if(!_json["Point5Offset"].IsString) { throw new SerializationException(); }  Point5Offset = _json["Point5Offset"]; }
        PostInit();
    }

    public TbLevelMap(int ID, int MapBlockID, string MapName, int Point1, int Point2, int Point3, int Point4, int Point5, string Point1Offset, string Point2Offset, string Point3Offset, string Point4Offset, string Point5Offset ) 
    {
        this.ID = ID;
        this.MapBlockID = MapBlockID;
        this.MapName = MapName;
        this.Point1 = Point1;
        this.Point2 = Point2;
        this.Point3 = Point3;
        this.Point4 = Point4;
        this.Point5 = Point5;
        this.Point1Offset = Point1Offset;
        this.Point2Offset = Point2Offset;
        this.Point3Offset = Point3Offset;
        this.Point4Offset = Point4Offset;
        this.Point5Offset = Point5Offset;
        PostInit();
    }

    public static TbLevelMap DeserializeTbLevelMap(JSONNode _json)
    {
        return new TbLevelMap(_json);
    }

    /// <summary>
    /// 生成点ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 所在地图块
    /// </summary>
    public int MapBlockID { get; private set; }
    /// <summary>
    /// 所在地图 ID
    /// </summary>
    public string MapName { get; private set; }
    /// <summary>
    /// 生成点1
    /// </summary>
    public int Point1 { get; private set; }
    /// <summary>
    /// 生成点2
    /// </summary>
    public int Point2 { get; private set; }
    /// <summary>
    /// 生成点3
    /// </summary>
    public int Point3 { get; private set; }
    /// <summary>
    /// 生成点4
    /// </summary>
    public int Point4 { get; private set; }
    /// <summary>
    /// 生成点5
    /// </summary>
    public int Point5 { get; private set; }
    /// <summary>
    /// 生成点1偏移量
    /// </summary>
    public string Point1Offset { get; private set; }
    /// <summary>
    /// 生成点2偏移量
    /// </summary>
    public string Point2Offset { get; private set; }
    /// <summary>
    /// 生成点3偏移量
    /// </summary>
    public string Point3Offset { get; private set; }
    /// <summary>
    /// 生成点4偏移量
    /// </summary>
    public string Point4Offset { get; private set; }
    /// <summary>
    /// 生成点5偏移量
    /// </summary>
    public string Point5Offset { get; private set; }

    public const int __ID__ = 1863824358;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "MapBlockID:" + MapBlockID + ","
        + "MapName:" + MapName + ","
        + "Point1:" + Point1 + ","
        + "Point2:" + Point2 + ","
        + "Point3:" + Point3 + ","
        + "Point4:" + Point4 + ","
        + "Point5:" + Point5 + ","
        + "Point1Offset:" + Point1Offset + ","
        + "Point2Offset:" + Point2Offset + ","
        + "Point3Offset:" + Point3Offset + ","
        + "Point4Offset:" + Point4Offset + ","
        + "Point5Offset:" + Point5Offset + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
