//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbPowerShop :  Bright.Config.BeanBase 
{
    public TbPowerShop(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["Power"].IsNumber) { throw new SerializationException(); }  Power = _json["Power"]; }
        { if(!_json["Diamond"].IsNumber) { throw new SerializationException(); }  Diamond = _json["Diamond"]; }
        PostInit();
    }

    public TbPowerShop(int ID, int Power, int Diamond ) 
    {
        this.ID = ID;
        this.Power = Power;
        this.Diamond = Diamond;
        PostInit();
    }

    public static TbPowerShop DeserializeTbPowerShop(JSONNode _json)
    {
        return new TbPowerShop(_json);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 恢复数量
    /// </summary>
    public int Power { get; private set; }
    /// <summary>
    /// 消耗钻石
    /// </summary>
    public int Diamond { get; private set; }

    public const int __ID__ = 150594221;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Power:" + Power + ","
        + "Diamond:" + Diamond + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
