//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbSceneRes :  Bright.Config.BeanBase 
{
    public TbSceneRes(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["ScenePath"].IsString) { throw new SerializationException(); }  ScenePath = _json["ScenePath"]; }
        PostInit();
    }

    public TbSceneRes(int ID, string ScenePath ) 
    {
        this.ID = ID;
        this.ScenePath = ScenePath;
        PostInit();
    }

    public static TbSceneRes DeserializeTbSceneRes(JSONNode _json)
    {
        return new TbSceneRes(_json);
    }

    /// <summary>
    /// 场景资源ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 场景资源地址
    /// </summary>
    public string ScenePath { get; private set; }

    public const int __ID__ = -1075000030;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "ScenePath:" + ScenePath + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
